/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BeforeAndAfterRouteImport } from './routes/before-and-after'
import { Route as BulkOrdersRouteImport } from './routes/bulk-orders'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FinishedProductsRouteImport } from './routes/finished-products'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MiscellaneousRouteImport } from './routes/miscellaneous'
import { Route as PuStoneRouteImport } from './routes/pu-stone'
import { Route as UvMarbleRouteImport } from './routes/uv-marble'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as WpcDeckingRouteImport } from './routes/wpc-decking'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminQuotesRouteImport } from './routes/admin/quotes'
import { Route as WpcPanelsIndexRouteImport } from './routes/wpc-panels/index'
import { Route as WpcPanelsAcousticRouteImport } from './routes/wpc-panels/acoustic'
import { Route as WpcPanelsIndoorRouteImport } from './routes/wpc-panels/indoor'
import { Route as WpcPanelsOutdoorRouteImport } from './routes/wpc-panels/outdoor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BeforeAndAfterRoute = BeforeAndAfterRouteImport.update({
  id: '/before-and-after',
  path: '/before-and-after',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrdersRoute = BulkOrdersRouteImport.update({
  id: '/bulk-orders',
  path: '/bulk-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishedProductsRoute = FinishedProductsRouteImport.update({
  id: '/finished-products',
  path: '/finished-products',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MiscellaneousRoute = MiscellaneousRouteImport.update({
  id: '/miscellaneous',
  path: '/miscellaneous',
  getParentRoute: () => rootRouteImport,
} as any)
const PuStoneRoute = PuStoneRouteImport.update({
  id: '/pu-stone',
  path: '/pu-stone',
  getParentRoute: () => rootRouteImport,
} as any)
const UvMarbleRoute = UvMarbleRouteImport.update({
  id: '/uv-marble',
  path: '/uv-marble',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const WpcDeckingRoute = WpcDeckingRouteImport.update({
  id: '/wpc-decking',
  path: '/wpc-decking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/admin/quotes',
  path: '/admin/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const WpcPanelsIndexRoute = WpcPanelsIndexRouteImport.update({
  id: '/wpc-panels/',
  path: '/wpc-panels/',
  getParentRoute: () => rootRouteImport,
} as any)
const WpcPanelsAcousticRoute = WpcPanelsAcousticRouteImport.update({
  id: '/wpc-panels/acoustic',
  path: '/wpc-panels/acoustic',
  getParentRoute: () => rootRouteImport,
} as any)
const WpcPanelsIndoorRoute = WpcPanelsIndoorRouteImport.update({
  id: '/wpc-panels/indoor',
  path: '/wpc-panels/indoor',
  getParentRoute: () => rootRouteImport,
} as any)
const WpcPanelsOutdoorRoute = WpcPanelsOutdoorRouteImport.update({
  id: '/wpc-panels/outdoor',
  path: '/wpc-panels/outdoor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/before-and-after': typeof BeforeAndAfterRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/finished-products': typeof FinishedProductsRoute
  '/gallery': typeof GalleryRoute
  '/miscellaneous': typeof MiscellaneousRoute
  '/pu-stone': typeof PuStoneRoute
  '/uv-marble': typeof UvMarbleRoute
  '/why-us': typeof WhyUsRoute
  '/wpc-decking': typeof WpcDeckingRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/wpc-panels/acoustic': typeof WpcPanelsAcousticRoute
  '/wpc-panels/indoor': typeof WpcPanelsIndoorRoute
  '/wpc-panels/outdoor': typeof WpcPanelsOutdoorRoute
  '/admin/': typeof AdminIndexRoute
  '/wpc-panels/': typeof WpcPanelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/before-and-after': typeof BeforeAndAfterRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/finished-products': typeof FinishedProductsRoute
  '/gallery': typeof GalleryRoute
  '/miscellaneous': typeof MiscellaneousRoute
  '/pu-stone': typeof PuStoneRoute
  '/uv-marble': typeof UvMarbleRoute
  '/why-us': typeof WhyUsRoute
  '/wpc-decking': typeof WpcDeckingRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/wpc-panels/acoustic': typeof WpcPanelsAcousticRoute
  '/wpc-panels/indoor': typeof WpcPanelsIndoorRoute
  '/wpc-panels/outdoor': typeof WpcPanelsOutdoorRoute
  '/admin': typeof AdminIndexRoute
  '/wpc-panels': typeof WpcPanelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/before-and-after': typeof BeforeAndAfterRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/finished-products': typeof FinishedProductsRoute
  '/gallery': typeof GalleryRoute
  '/miscellaneous': typeof MiscellaneousRoute
  '/pu-stone': typeof PuStoneRoute
  '/uv-marble': typeof UvMarbleRoute
  '/why-us': typeof WhyUsRoute
  '/wpc-decking': typeof WpcDeckingRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/wpc-panels/acoustic': typeof WpcPanelsAcousticRoute
  '/wpc-panels/indoor': typeof WpcPanelsIndoorRoute
  '/wpc-panels/outdoor': typeof WpcPanelsOutdoorRoute
  '/admin/': typeof AdminIndexRoute
  '/wpc-panels/': typeof WpcPanelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/before-and-after'
    | '/bulk-orders'
    | '/contact'
    | '/faq'
    | '/finished-products'
    | '/gallery'
    | '/miscellaneous'
    | '/pu-stone'
    | '/uv-marble'
    | '/why-us'
    | '/wpc-decking'
    | '/admin/contacts'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/products'
    | '/admin/quotes'
    | '/wpc-panels/acoustic'
    | '/wpc-panels/indoor'
    | '/wpc-panels/outdoor'
    | '/admin/'
    | '/wpc-panels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/before-and-after'
    | '/bulk-orders'
    | '/contact'
    | '/faq'
    | '/finished-products'
    | '/gallery'
    | '/miscellaneous'
    | '/pu-stone'
    | '/uv-marble'
    | '/why-us'
    | '/wpc-decking'
    | '/admin/contacts'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/products'
    | '/admin/quotes'
    | '/wpc-panels/acoustic'
    | '/wpc-panels/indoor'
    | '/wpc-panels/outdoor'
    | '/admin'
    | '/wpc-panels'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/before-and-after'
    | '/bulk-orders'
    | '/contact'
    | '/faq'
    | '/finished-products'
    | '/gallery'
    | '/miscellaneous'
    | '/pu-stone'
    | '/uv-marble'
    | '/why-us'
    | '/wpc-decking'
    | '/admin/contacts'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/products'
    | '/admin/quotes'
    | '/wpc-panels/acoustic'
    | '/wpc-panels/indoor'
    | '/wpc-panels/outdoor'
    | '/admin/'
    | '/wpc-panels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeforeAndAfterRoute: typeof BeforeAndAfterRoute
  BulkOrdersRoute: typeof BulkOrdersRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FinishedProductsRoute: typeof FinishedProductsRoute
  GalleryRoute: typeof GalleryRoute
  MiscellaneousRoute: typeof MiscellaneousRoute
  PuStoneRoute: typeof PuStoneRoute
  UvMarbleRoute: typeof UvMarbleRoute
  WhyUsRoute: typeof WhyUsRoute
  WpcDeckingRoute: typeof WpcDeckingRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  WpcPanelsAcousticRoute: typeof WpcPanelsAcousticRoute
  WpcPanelsIndoorRoute: typeof WpcPanelsIndoorRoute
  WpcPanelsOutdoorRoute: typeof WpcPanelsOutdoorRoute
  AdminIndexRoute: typeof AdminIndexRoute
  WpcPanelsIndexRoute: typeof WpcPanelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/before-and-after': {
      id: '/before-and-after'
      path: '/before-and-after'
      fullPath: '/before-and-after'
      preLoaderRoute: typeof BeforeAndAfterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-orders': {
      id: '/bulk-orders'
      path: '/bulk-orders'
      fullPath: '/bulk-orders'
      preLoaderRoute: typeof BulkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finished-products': {
      id: '/finished-products'
      path: '/finished-products'
      fullPath: '/finished-products'
      preLoaderRoute: typeof FinishedProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miscellaneous': {
      id: '/miscellaneous'
      path: '/miscellaneous'
      fullPath: '/miscellaneous'
      preLoaderRoute: typeof MiscellaneousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pu-stone': {
      id: '/pu-stone'
      path: '/pu-stone'
      fullPath: '/pu-stone'
      preLoaderRoute: typeof PuStoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uv-marble': {
      id: '/uv-marble'
      path: '/uv-marble'
      fullPath: '/uv-marble'
      preLoaderRoute: typeof UvMarbleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wpc-decking': {
      id: '/wpc-decking'
      path: '/wpc-decking'
      fullPath: '/wpc-decking'
      preLoaderRoute: typeof WpcDeckingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/admin/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wpc-panels/': {
      id: '/wpc-panels/'
      path: '/wpc-panels'
      fullPath: '/wpc-panels/'
      preLoaderRoute: typeof WpcPanelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wpc-panels/acoustic': {
      id: '/wpc-panels/acoustic'
      path: '/wpc-panels/acoustic'
      fullPath: '/wpc-panels/acoustic'
      preLoaderRoute: typeof WpcPanelsAcousticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wpc-panels/indoor': {
      id: '/wpc-panels/indoor'
      path: '/wpc-panels/indoor'
      fullPath: '/wpc-panels/indoor'
      preLoaderRoute: typeof WpcPanelsIndoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wpc-panels/outdoor': {
      id: '/wpc-panels/outdoor'
      path: '/wpc-panels/outdoor'
      fullPath: '/wpc-panels/outdoor'
      preLoaderRoute: typeof WpcPanelsOutdoorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeforeAndAfterRoute: BeforeAndAfterRoute,
  BulkOrdersRoute: BulkOrdersRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FinishedProductsRoute: FinishedProductsRoute,
  GalleryRoute: GalleryRoute,
  MiscellaneousRoute: MiscellaneousRoute,
  PuStoneRoute: PuStoneRoute,
  UvMarbleRoute: UvMarbleRoute,
  WhyUsRoute: WhyUsRoute,
  WpcDeckingRoute: WpcDeckingRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  WpcPanelsAcousticRoute: WpcPanelsAcousticRoute,
  WpcPanelsIndoorRoute: WpcPanelsIndoorRoute,
  WpcPanelsOutdoorRoute: WpcPanelsOutdoorRoute,
  AdminIndexRoute: AdminIndexRoute,
  WpcPanelsIndexRoute: WpcPanelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
